# Generated by Django 5.0.7 on 2024-07-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(default='Technology', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default='Global', max_length=255),
        ),
    ]
