name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io

      - name: Build Docker image
        run: |
          docker-compose build

      - name: Run Docker container
        run: |
          docker-compose up -d

      - name: Run tests
        run: |
          docker-compose exec -T web python manage.py test

      - name: Collect static files
        run: |
          docker-compose exec -T web python manage.py collectstatic --noinput

      - name: Shutdown Docker containers
        run: |
          docker-compose down
