name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker image
        run: |
          docker-compose build

      - name: Run Docker container
        run: |
          docker-compose up -d

      - name: Run tests
        run: |
          docker-compose exec -T web python manage.py test

      - name: Collect static files
        run: |
          docker-compose exec -T web python manage.py collectstatic --noinput

      - name: Shutdown Docker containers
        run: |
          docker-compose down
